Repository ISISComputingGroup/EPICS-ZFCNTRL, pull requests merged in 2019-12, with the labels that each got.

#1 Move dbs and SNL to support module rather than IOC.
  .gitignore
  Makefile
  configure/CONFIG
  configure/CONFIG_APP
  configure/Makefile
  configure/RELEASE
  configure/RULES
  configure/RULES_DIRS
  configure/RULES_TOP
  zfcntrlSup/Makefile
  zfcntrlSup/seqPVmacros.h
  zfcntrlSup/zero_field.st
  zfcntrlSup/zf_pv_definitions.h
  zfcntrlSup/zfcntrl.db
  zfcntrlSup/zfcntrl.dbd
  zfcntrlSup/zfcntrl_axis.substitutions
  zfcntrlSup/zfcntrl_axis.template
Labels: size/XXL

#2 Fixes use of time by using epics functions
  zfcntrlSup/zero_field.st
  zfcntrlSup/zfcntrl_axis.template
Labels: size/S

#3 Move declaration for C89 compatibility
  zfcntrlSup/zero_field.st
Labels: size/XS
