Repository ISISComputingGroup/EPICS-ZFCNTRL, pull requests merged in 2020-03, with the labels that each got.

#7 set voltage limits automatically
  zfcntrlSup/zero_field.st
  zfcntrlSup/zf_pv_definitions.h
  zfcntrlSup/zfcntrl.db
  zfcntrlSup/zfcntrl_axis.template
Labels: size/L

#9 Add math.h to get correct return type for fabs()
  zfcntrlSup/zero_field.st
Labels: size/XS

#8 Change STABLITY PV to AT_SETPOINT
  zfcntrlSup/zero_field.st
  zfcntrlSup/zf_pv_definitions.h
  zfcntrlSup/zfcntrl.db
Labels: size/M
